# sudo -u postgres psql
# create user whatscommerce with password 'whatscommerce';
# create database "whatscommerce-api-dev" owner whatscommerce;
# create database "whatscommerce-api-test" owner whatscommerce;
# create database "whatscommerce-api-prod" owner whatscommerce;
# alter user whatscommerce superuser createrole createdb replication;
# \q

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  # username: postgres
  # password: 3960
  username: whatscommerce
  password: whatscommerce
  host: localhost
  port: 5432

development:
 <<: *default
 database: whatscommerce-api-dev

test:
 <<: *default
 database: whatscommerce-api-test

production:
 <<: *default
 database: whatscommerce-api-prod
